name: CI windows-msvc

on:
  push:
    branches: [main, master, contour]
  pull_request:

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure
        run: cmake --preset windows-msvc-debug
      - name: Build
        run: cmake --build --preset windows-msvc-debug
      - name: Test
        run: ctest --preset windows-msvc-debug
